server:
  port: 9030

spring:
  application:
    name: youxuan-search-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

youxuan:
  elasticsearch:
    uris: http://localhost:9200
