server:
  port: 9030

spring:
  application:
    name: youxuan-search-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

youxuan:
  elasticsearch:
    uris: http://localhost:9200
