server:
  port: 9060

spring:
  application:
    name: youxuan-file-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

youxuan:
  minio:
    endpoint: http://localhost:9100
    public-endpoint: http://localhost:9100
    access-key: minioadmin
    secret-key: minioadmin
    bucket: youxuan-mall
